### ISSUE TITLE
Sends browser notifications for activity feed. 

### ISSUE THREAD

**Issue by GBD-Media** [muraliwebworld/push-notification-plugin-for-wordpress-websites#5]
I have tried to change the settings to only private messages and friend requests, but (1) it notifies everyone whenever someone posts and activity update.
I have also checked the front end settings, (2)the button does not press to save. Maybe it's a mobile only issue as I have tried mostly on mobile device.

**Comment by muraliwebworld** [comment]
It is resolved in 1.80 version onwards, please download latest version 1.81 from https://wordpress.org/plugins/push-notification-for-post-and-buddypress/ ...sorry for late reply, usually i check issues/emails about this plugin in wordpress org plugin forum or in my email id murali@indiacitys.com.
